name: motel_go
description: "Motel List Challenge."
publish_to: 'none' 
version: 1.0.0+5

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  app:
    path: app
  flutter_launcher_icons: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "app/lib/assets/images/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
