name: feature_module_base
description: "Dependencies shared by the feature modules."
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  app:
    path: ../../app

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:

    
