name: app
description: "App Project Base."
version: 0.0.2
homepage:
publish_to: none

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  feature_module_base: 
    path: ../feature_modules/feature_module_base
  bloc: ^9.0.0
  equatable: ^2.0.7
  flutter_bloc: ^9.0.0
  http: ^1.3.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  material_symbols_icons: ^4.2801.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  json_serializable: ^6.9.3
  mocktail: ^1.0.4

flutter:

