name: Flutter CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Set up Flutter
        run: |
          git clone https://github.com/flutter/flutter.git
          echo "FLUTTER_ROOT=$(pwd)/flutter" >> $GITHUB_ENV
          echo "PATH=\$FLUTTER_ROOT/bin:\$PATH" >> $GITHUB_ENV
          source $GITHUB_ENV
          export PATH="$PATH:`pwd`/flutter/bin"
          flutter --version

      - name: Install dependencies
        run: |
          source $GITHUB_ENV
          flutter pub get

      - name: Run tests
        run: |
          source $GITHUB_ENV
          flutter test

      - name: Build APK
        run: |
          source $GITHUB_ENV
          flutter build apk --release

      - name: Rename APK
        run: mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/motel_go.apk

      - name: Upload APK to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/motel_go.apk
